version: '3'

services:
  my_app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: "8080"
    ports:
      - "3000:8080"

  db:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_PASSWORD: nHUxDpnvNxEIldD4WLuB6rhpP1BoU3uF
      POSTGRES_DB: mydb_0nle
    ports:
      - "5432:5432"
