version: '3'

services:
  my_app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: "8080"
    ports:
      - "3000:8080"

  db:
    image: postgres:15.4-alpine3.18
